# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lurl', models.CharField(max_length=256)),
                ('Surl', models.CharField(blank=True, max_length=32)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
