# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161129_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Lurl',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
