# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161129_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='Surl',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
