# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161129_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='Views',
            field=models.IntegerField(default=0, max_length=32),
        ),
    ]
